<Project Sdk="Microsoft.NET.Sdk.Razor">

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Spectre.Console" />
    <PackageReference Include="ColorCode.Core" />
    <PackageReference Include="Markdig" />
  </ItemGroup>
  <Import Project="$(RepoRoot)/nuget/nuget-package.props" />

  <ItemGroup>
    <InternalsVisibleTo Include="RazorConsole.Tests" />
    <InternalsVisibleTo Include="RazorConsole.Website" />
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
  </ItemGroup>

  <PropertyGroup>
    <Version>0.5.0-tvkit.1</Version>
    <IsPackable>false</IsPackable>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

  <PropertyGroup>
    <NoWarn>$(NoWarn);BL0007</NoWarn>
  </PropertyGroup>

  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

</Project>